# Generated by Django 5.0 on 2024-09-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATPDocModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('customer_code_edrpou', models.IntegerField(blank=True, null=True, verbose_name='Code EDRPOU')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=200, verbose_name='Vehicle Number')),
                ('brand', models.CharField(blank=True, max_length=200, verbose_name='Brand')),
                ('model', models.CharField(blank=True, max_length=200, verbose_name='Model')),
                ('year', models.IntegerField(blank=True, verbose_name='Year')),
            ],
        ),
        migrations.CreateModel(
            name='TovModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_edrpou', models.IntegerField(blank=True, default=0, max_length=8, verbose_name='Code EDRPOU')),
                ('tov_name', models.CharField(blank=True, max_length=200, verbose_name='TOV Name')),
                ('full_tov_name', models.CharField(blank=True, max_length=200, verbose_name='Full TOV Name')),
                ('director_name', models.CharField(blank=True, max_length=200, verbose_name='Name of Director')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Address')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=200, verbose_name='Phone')),
                ('gender', models.CharField(blank=True, max_length=200, verbose_name='Gender')),
                ('iban', models.CharField(blank=True, max_length=200, verbose_name='IBAN')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='Bank Name')),
                ('mfo', models.IntegerField(blank=True, default=0, verbose_name='MFO')),
                ('atp_docs', models.ManyToManyField(blank=True, related_name='tovs', to='documents.atpdocmodel', verbose_name='ATP Documents')),
                ('vehicles', models.ManyToManyField(blank=True, related_name='tovs', to='documents.vehiclemodel', verbose_name='Vehicles')),
            ],
        ),
        migrations.CreateModel(
            name='FopModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_edrpou', models.IntegerField(blank=True, default=0, max_length=10, verbose_name='Code EDRPOU')),
                ('fop_name', models.CharField(blank=True, max_length=200, verbose_name='FOP Name')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Address')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=200, verbose_name='Phone')),
                ('gender', models.CharField(blank=True, max_length=200, verbose_name='Gender')),
                ('iban', models.CharField(blank=True, max_length=200, verbose_name='IBAN')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='Bank Name')),
                ('mfo', models.IntegerField(blank=True, default=0, verbose_name='MFO')),
                ('atp_docs', models.ManyToManyField(blank=True, related_name='fops', to='documents.atpdocmodel', verbose_name='ATP Documents')),
                ('vehicles', models.ManyToManyField(blank=True, related_name='fops', to='documents.vehiclemodel', verbose_name='Vehicles')),
            ],
        ),
    ]
