# Generated by Django 5.0 on 2024-09-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_choice', models.CharField(choices=[('ATP', 'ATP'), ('OFFICE', 'OFFICE')], default='ATP', verbose_name='Contract Choice')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('customer_code_edrpou', models.CharField(blank=True, null=True, verbose_name='Code EDRPOU')),
            ],
        ),
        migrations.RemoveField(
            model_name='fopmodel',
            name='atp_docs',
        ),
        migrations.RemoveField(
            model_name='tovmodel',
            name='atp_docs',
        ),
        migrations.RemoveField(
            model_name='fopmodel',
            name='vehicles',
        ),
        migrations.RemoveField(
            model_name='tovmodel',
            name='vehicles',
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='brand',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='model',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Vehicle Number'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='year',
            field=models.CharField(blank=True, null=True, verbose_name='Year'),
        ),
        migrations.CreateModel(
            name='BusinessEntitiesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_entity', models.CharField(choices=[('TOV', 'TOV'), ('FOP', 'FOP')], default='FOP', max_length=3)),
                ('code_edrpou', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Code EDRPOU')),
                ('fop_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='FOP Name')),
                ('tov_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='TOV Name')),
                ('full_tov_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Full TOV Name')),
                ('director_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name of Director')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Phone')),
                ('gender', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gender')),
                ('iban', models.CharField(blank=True, max_length=200, null=True, verbose_name='IBAN')),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bank Name')),
                ('mfo', models.CharField(blank=True, null=True, verbose_name='MFO')),
                ('vehicles', models.ManyToManyField(blank=True, related_name='business_entities', to='documents.vehiclemodel', verbose_name='Vehicles')),
                ('contract', models.ManyToManyField(blank=True, related_name='business_entities', to='documents.contractmodel', verbose_name='Contract Documents')),
            ],
        ),
        migrations.DeleteModel(
            name='ATPDocModel',
        ),
        migrations.DeleteModel(
            name='FopModel',
        ),
        migrations.DeleteModel(
            name='TovModel',
        ),
    ]
