# Generated by Django 5.0 on 2024-09-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_contractmodel_remove_fopmodel_atp_docs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessentitiesmodel',
            name='gender',
            field=models.CharField(choices=[('M', 'який'), ('F', 'яка')], default='M', max_length=5, verbose_name='Gender'),
        ),
    ]
